name: build-test-deploy
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Run npm install
        run: npm install
      - name: Run npm build
        run: npm run build
      - name: Run npm tests
        run: npm test
